name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'pdf-compressor-pwa/package-lock.json'

      - name: Install dependencies
        working-directory: pdf-compressor-pwa
        run: npm ci --no-audit --no-fund

      - name: Build PWA
        working-directory: pdf-compressor-pwa
        run: npm run build

      - name: Upload dist artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: pdf-compressor-pwa/dist

